//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatarCulturaWpf.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.Comments = new HashSet<Comment>();
            this.Stars = new HashSet<Star>();
        }
    
        public int IdObject { get; set; }
        public int IdType { get; set; }
        public string Name { get; set; }
        public string ObjectPhoto { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Star> Stars { get; set; }

        public string GetObjectPhoto
        {
            get
            {
                if (ObjectPhoto is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + ObjectPhoto.Trim();
            }
        }
    }
}
