 //------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatarCulturaWpf.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.Events = new HashSet<Event>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int IdObject { get; set; }
        public int IdType { get; set; }
        public string Name { get; set; }
        public string ObjectPhoto { get; set; }
        public string Description { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }

        public string GetObjectPhoto
        {
            get
            {
                if (ObjectPhoto is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + ObjectPhoto.Trim();
            }
        }

        public string Geo
        {
            get
            {
                if (Latitude == 0)
                    return null;
                return $"{Latitude.ToString().Replace(",", ".")} , {Longitude.ToString().Replace(",", ".")}";
            }
        }

        public string GetRate
        {
            get
            {
                double? x = 0;
                foreach (Comment z in Comments)
                {
                    x += z.Star;
                }
                if (x == 0)
                    return "Нет отзывов";

                return ((double)x / Comments.Count).ToString("0.00");

            }
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
