//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatarCulturaWpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int IdSale { get; set; }
        public int IdKey { get; set; }
        public int IdUser { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
    
        public virtual Key Key { get; set; }
        public virtual User User { get; set; }

        public string GetEvent
        {
            get
            {
                return Key.Event.Name;
            }
        }

        public DateTime GetStartDateEvent
        {
            get
            {
                return (DateTime)Key.Event.DateStarEvent;
            }
        }

        public DateTime GetEndDateEvent
        {
            get
            {
                return (DateTime)Key.Event.DateEndEvent;
            }
        }
    }
}
