//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatarCulturaWpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Star
    {
        public int IdStar { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdObject { get; set; }
        public Nullable<int> Star1 { get; set; }
    
        public virtual User User { get; set; }
        public virtual Object Object { get; set; }
    }
}
